### ISSUE TITLE
Consistent error when trying to evaluate character animation

### ISSUE THREAD

**Issue by KennyPell** [richard-roberts/SalientPosesMaya#28]
Here is the error

Traceback (most recent call last):
  File "C:/Users/Admin/Documents/maya/2018/scripts\salient_menu.py", line 183, in do_select
    self.update_visualization()
  File "C:/Users/Admin/Documents/maya/2018/scripts\salient_menu.py", line 237, in update_visualization
    ys = [self.get_error(n, normalized=True) for n in range(min_keyframes, max_keyframes + 1)]
  File "C:/Users/Admin/Documents/maya/2018/scripts\salient_menu.py", line 220, in get_error
    return self.selections[n]["error"] / self.selections[min_n]["error"]
ZeroDivisionError: float division by zero // 

Using Maya 2018.4

If I make a simple scene with a moving object everything works fine, this comes when I am trying to evaluate a character, even if its just a single bone.

**Comment by richard-roberts** [comment]
Thanks for the issue.

The divide by zero error occurs here because the best selection has zero error. That seems expected, not sure why I haven't seen it before. Could you share the scene file with the single bone, I'll try to make a fix sometime today!

**Comment by richard-roberts** [comment]
Resolved with #29 – interface no longer opens until the plugin is initialized correctly.
