### ISSUE TITLE
Building on Windows error (Maya 2017, SalientPoses v0.3)

### ISSUE THREAD

**Issue by charliewales** [richard-roberts/SalientPosesMaya#31]
Hi Robert, thanks for sharing this. I'm trying to build version 0.3 on windows with Visual Studio 15 2017 for Maya 2017. But I get an error I do not know how to solve. Would It be possible to have a Maya 2017 for windows version compiled as well? I saw you provided 2018 and 2019 but I'm on 2017.

I set the IDE to Visual Studio 15 2017 Maya version to 2017 but to no avail. 
Thanks again.

This is the error output. 

CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindMaya.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Maya", but
  CMake did not find one.

  Could not find a package configuration file provided by "Maya" with any of
  the following names:

    MayaConfig.cmake
    maya-config.cmake

  Add the installation prefix of "Maya" to CMAKE_PREFIX_PATH or set
  "Maya_DIR" to a directory containing one of the above files.  If "Maya"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by richard-roberts** [comment]
Hi there, first off thanks for having at go at this! If you just wanted to try things out, the [v0.2 release](https://github.com/richard-roberts/SalientPosesMaya/releases/tag/0.2) has a version compiled for 2017.

As for the current version, I fear that the Python code for the UI won't be immediately compilable with Maya 2017 (it seems like Maya has slowly moving all UI stuff toward PySide over the last few years).  Not sure if much would need to change, probably just a few lines here and there. Try getting the plugin compiled first, from there I can help resolve any UI issues.

Anyway, **back to the error**, CMake is trying to find a file that explains how it can find your Maya installation. The file its looking for is included inside Chad Vernon's `cgcmake` project, which is included as a submodule. So, my guess is that the file `cgcmake\modules\FindMaya.cmake` is missing from your copy of the project. Check that the submodules are initialized (if you're using command line then `git submodule init && git submodule update`), and then check that the file exists. Let me know if that helps!

**Comment by charliewales** [comment]
Hey, yeah I have v0.2 up and running on Maya 2017, just wanted to be up to date with your latest changes.

So I did 'git clone' your SalientPoses repo:

    git clone https://github.com/richard-roberts/SalientPosesMaya.git

Then, inside the created SalientPosesMaya folder I run:

    git submodule init && git submodule update

Now when I run setup.bat using 

IDE: Visual Studio 15 2017
Maya Version: 2017

The solution is built with no errors. Thanks.

I had create a x64 and change this relative path to an absolute path in some files and It compiled:

../eigen-git-mirror/Eigen/Dense

Time to test it. Thanks a lot and cheers.

**Comment by richard-roberts** [comment]
That's great, glad it helped. Hmm yeah, depending on the Visual Studio setup, you may need to configure the x64 thing. If you check the Visual Studio project configurations, you should find one called "install". If you build the install version, Visual Studio will create the Maya-ready folder for you.

Regarding the UI, the current version is somewhat a work in progress (in terms of UI design). I'll put together a more final interface based on how people find it, so do let me know of both positive or negative feedback!
